### Folders Configuration ###
ConfigDir="config"
FunctionsDir="functions"

### Rsync Configuration ###
cmdlines=" --delete --download-metadata --downloadcomps --gpgcheck -n" 
## WIP: Easy Config ##
# TODO: Enable translation of below config variablers to proper cmdlines.
Delete="Yes"
Download_Metadata="Yes"
Download_Comps="Yes"
GPG_Check="Yes"
Newest_Only="Yes"
Source="No"
URLs="No"

########################################################################################
# You can use these:
#  --delete
              # Delete local packages no longer present in repository.
              
# --download-metadata
  #            Download all repository metadata. Downloaded copy is instantly usable as a repository, no need to run cre‐
  #            aterepo_c on it. When the option is used with --newest-only, only latest packages will be downloaded,  but
  #            metadata will still contain older packages. It might be useful to update metadata using createrepo_c --up‐
  #            date to remove the packages with missing RPM files from metadata. Otherwise, DNF ends with an error due to
  #            the missing files whenever it tries to download older packages.

# -m, --downloadcomps
  #            Also download and uncompress comps.xml. Consider using --download-metadata option which will download  all
  #            available repository metadata.

#  -g, --gpgcheck
 #             Remove packages that fail GPG signature checking after downloading. Exit code is 1 if at least one package
 #             was  removed.   Note that for repositories with gpgcheck=0 set in their configuration the GPG signature is
 #             not checked even with this option used.

#  -n, --newest-only
 #              Download only newest packages per-repo.

# --source
   #           Download only source packages.

#       -u, --urls
  #            Just print urls of what would be downloaded, don't download.


