########## Excludes Configuration ##########
# TODO: Remove the following $excludes variable after further testing
# excludes="*-debug*,*-rt-*"

ExcludesFile="~/dnf5-repos/Fedora/excludes/excludes-filtered2.list"
CommaExcludesFile="~/dnf5-repos/Fedora/excludes/excludes-filtered2-commas.list"


