#!/bin/env bash

##### Corrected by Google AI and confirmed working as of 04/02/2026 #####
### Updated to enable excludes and needs testing as of 04/26/2026 ###

## FIXME: Even with usage function run disabled, excludes shows several lines as "command not found" and usage still displays.
##		Study UpdateRepo.bfunc to find error.


############################################################################
   # ShellCheck - Disable Unnecessary Checks #				#
   # shellcheck source=/dev/null					#
   # shellcheck disable=SC2034  # Unused variables left for readability	#
############################################################################


########## Define Main Variables ##########

# Program Version
ProgVersion="26.07_r2"

# Define Folders
ConfigFoler="config"
FuncFolder="functions"
ExcludesFolder="excludes"

# CheckVariable
 CheckVarFile="$FuncFolder/CheckVariable.bfunc"

# FuncFile
 FuncFile="$FuncFolder/UpdateRepo.bfunc"

# Cecho
 CechoFile="$FuncFolder/Cecho.bfunc"


########## Define Program & Args Variables ##########

prog="reposync"
args=" -n -m --delete"


######### Excludes Configuration ##########
# TODO: Remove the following $excludes variable after further testing
# excludes="*-debug*,*-rt-*"


## ExcludesFile="excludes-filtered2.list"
## CommaExcludesFile="excludes-filtered2-commas.list"

 ExcludesFile="$ExcludesFolder/excludes-filtered2.list"
 CommaExcludesFile="$ExcludesFolder/excludes-filtered2-commas.list"


##########################################################################################################################################
## FIXME: Need to change code so that contents of files are placed into a variable.							##
##		Sourcing runs the package names, so 'kernel-debug' listed in the file actually runs the command 'kernel-debug'.		##
##		Do NOT source excludes files!												##
##########################################################################################################################################

